[2024-04-04T08:37:06.665+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: real_estates.load_to_one_c scheduled__2024-04-03T00:00:00+00:00 [queued]>
[2024-04-04T08:37:06.686+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: real_estates.load_to_one_c scheduled__2024-04-03T00:00:00+00:00 [queued]>
[2024-04-04T08:37:06.687+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-04-04T08:37:06.716+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): load_to_one_c> on 2024-04-03 00:00:00+00:00
[2024-04-04T08:37:06.732+0000] {standard_task_runner.py:60} INFO - Started process 3838 to run task
[2024-04-04T08:37:06.740+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'real_estates', 'load_to_one_c', 'scheduled__2024-04-03T00:00:00+00:00', '--job-id', '203', '--raw', '--subdir', 'DAGS_FOLDER/real_estates/__init__.py', '--cfg-path', '/tmp/tmpr57yef3g']
[2024-04-04T08:37:06.746+0000] {standard_task_runner.py:88} INFO - Job 203: Subtask load_to_one_c
[2024-04-04T08:37:07.166+0000] {task_command.py:423} INFO - Running <TaskInstance: real_estates.load_to_one_c scheduled__2024-04-03T00:00:00+00:00 [running]> on host 05a350db99a0
[2024-04-04T08:37:07.661+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='real_estates' AIRFLOW_CTX_TASK_ID='load_to_one_c' AIRFLOW_CTX_EXECUTION_DATE='2024-04-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-03T00:00:00+00:00'
[2024-04-04T08:37:07.664+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/real_estates/homes_jp/loaders/__init__.py", line 13, in load_to_one_c
    one_c(data)
  File "/opt/airflow/dags/real_estates/homes_jp/loaders/one_c.py", line 84, in one_c
    "Ward": item["ward_eng"],
KeyError: 'ward_eng'
[2024-04-04T08:37:07.680+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=real_estates, task_id=load_to_one_c, execution_date=20240403T000000, start_date=20240404T083706, end_date=20240404T083707
[2024-04-04T08:37:07.704+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 203 for task load_to_one_c ('ward_eng'; 3838)
[2024-04-04T08:37:07.755+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-04T08:37:07.797+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
