[2024-04-04T08:31:55.475+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: real_estates.load_to_one_c scheduled__2024-04-03T00:00:00+00:00 [queued]>
[2024-04-04T08:31:55.495+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: real_estates.load_to_one_c scheduled__2024-04-03T00:00:00+00:00 [queued]>
[2024-04-04T08:31:55.495+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-04T08:31:55.520+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): load_to_one_c> on 2024-04-03 00:00:00+00:00
[2024-04-04T08:31:55.534+0000] {standard_task_runner.py:60} INFO - Started process 3759 to run task
[2024-04-04T08:31:55.541+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'real_estates', 'load_to_one_c', 'scheduled__2024-04-03T00:00:00+00:00', '--job-id', '202', '--raw', '--subdir', 'DAGS_FOLDER/real_estates/__init__.py', '--cfg-path', '/tmp/tmpjda6_lzd']
[2024-04-04T08:31:55.546+0000] {standard_task_runner.py:88} INFO - Job 202: Subtask load_to_one_c
[2024-04-04T08:31:55.650+0000] {task_command.py:423} INFO - Running <TaskInstance: real_estates.load_to_one_c scheduled__2024-04-03T00:00:00+00:00 [running]> on host 05a350db99a0
[2024-04-04T08:31:56.422+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='real_estates' AIRFLOW_CTX_TASK_ID='load_to_one_c' AIRFLOW_CTX_EXECUTION_DATE='2024-04-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-03T00:00:00+00:00'
[2024-04-04T08:31:56.426+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/real_estates/homes_jp/loaders/__init__.py", line 13, in load_to_one_c
    one_c(data)
  File "/opt/airflow/dags/real_estates/homes_jp/loaders/one_c.py", line 50, in one_c
    "LocationDescription": item["Access"],
KeyError: 'Access'
[2024-04-04T08:31:56.444+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=real_estates, task_id=load_to_one_c, execution_date=20240403T000000, start_date=20240404T083155, end_date=20240404T083156
[2024-04-04T08:31:56.469+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 202 for task load_to_one_c ('Access'; 3759)
[2024-04-04T08:31:56.516+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-04T08:31:56.552+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
