[2024-04-08T04:58:35.470+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: real_estates.transform_parse_address manual__2024-04-08T03:55:40.228975+00:00 [queued]>
[2024-04-08T04:58:35.491+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: real_estates.transform_parse_address manual__2024-04-08T03:55:40.228975+00:00 [queued]>
[2024-04-08T04:58:35.491+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-04-08T04:58:35.516+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): transform_parse_address> on 2024-04-08 03:55:40.228975+00:00
[2024-04-08T04:58:35.531+0000] {standard_task_runner.py:60} INFO - Started process 79130 to run task
[2024-04-08T04:58:35.539+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'real_estates', 'transform_parse_address', 'manual__2024-04-08T03:55:40.228975+00:00', '--job-id', '319', '--raw', '--subdir', 'DAGS_FOLDER/real_estates/__init__.py', '--cfg-path', '/tmp/tmposco0z5q']
[2024-04-08T04:58:35.550+0000] {standard_task_runner.py:88} INFO - Job 319: Subtask transform_parse_address
[2024-04-08T04:58:35.959+0000] {task_command.py:423} INFO - Running <TaskInstance: real_estates.transform_parse_address manual__2024-04-08T03:55:40.228975+00:00 [running]> on host 05a350db99a0
[2024-04-08T04:58:42.087+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='real_estates' AIRFLOW_CTX_TASK_ID='transform_parse_address' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T03:55:40.228975+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-08T03:55:40.228975+00:00'
[2024-04-08T04:58:42.325+0000] {taskinstance.py:2731} ERROR - Task failed with exception
  + Exception Group Traceback (most recent call last):
  |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
  |     result = _execute_callable(context=context, **execute_callable_kwargs)
  |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
  |     return execute_callable(context=context, **execute_callable_kwargs)
  |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
  |     return_value = super().execute(context)
  |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
  |     return_value = self.execute_callable()
  |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
  |     return self.python_callable(*self.op_args, **self.op_kwargs)
  |   File "/opt/airflow/dags/real_estates/homes_jp/transformers/__init__.py", line 8, in transform_parse_address
  |     return trio.run(_transform_parse_address, data)
  |   File "/home/airflow/.local/lib/python3.8/site-packages/trio/_core/_run.py", line 2288, in run
  |     raise runner.main_task_outcome.error
  |   File "/opt/airflow/dags/real_estates/homes_jp/transformers/parse_address.py", line 56, in _transform_parse_address
  |     nursery.start_soon(translate_item, item, translated_data)
  |   File "/home/airflow/.local/lib/python3.8/site-packages/trio/_core/_run.py", line 954, in __aexit__
  |     raise combined_error_from_nursery
  | exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (3343 sub-exceptions)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/opt/airflow/dags/real_estates/homes_jp/transformers/parse_address.py", line 70, in translate_item
    |     data.update(address)
    | TypeError: 'coroutine' object is not iterable
    +---------------- 2 ----------------
    | Traceback (most recent call last):
    |   File "/opt/airflow/dags/real_estates/homes_jp/transformers/parse_address.py", line 70, in translate_item
    |     data.update(address)
    | TypeError: 'coroutine' object is not iterable
    +---------------- 3 ----------------
    | Traceback (most recent call last):
    |   File "/opt/airflow/dags/real_estates/homes_jp/transformers/parse_address.py", line 70, in translate_item
    |     data.update(address)
    | TypeError: 'coroutine' object is not iterable
    +---------------- 4 ----------------
    | Traceback (most recent call last):
    |   File "/opt/airflow/dags/real_estates/homes_jp/transformers/parse_address.py", line 70, in translate_item
    |     data.update(address)
    | TypeError: 'coroutine' object is not iterable
    +---------------- 5 ----------------
    | Traceback (most recent call last):
    |   File "/opt/airflow/dags/real_estates/homes_jp/transformers/parse_address.py", line 70, in translate_item
    |     data.update(address)
    | TypeError: 'coroutine' object is not iterable
    +---------------- 6 ----------------
    | Traceback (most recent call last):
    |   File "/opt/airflow/dags/real_estates/homes_jp/transformers/parse_address.py", line 70, in translate_item
    |     data.update(address)
    | TypeError: 'coroutine' object is not iterable
    +---------------- 7 ----------------
    | Traceback (most recent call last):
    |   File "/opt/airflow/dags/real_estates/homes_jp/transformers/parse_address.py", line 70, in translate_item
    |     data.update(address)
    | TypeError: 'coroutine' object is not iterable
    +---------------- 8 ----------------
    | Traceback (most recent call last):
    |   File "/opt/airflow/dags/real_estates/homes_jp/transformers/parse_address.py", line 70, in translate_item
    |     data.update(address)
    | TypeError: 'coroutine' object is not iterable
    +---------------- 9 ----------------
    | Traceback (most recent call last):
    |   File "/opt/airflow/dags/real_estates/homes_jp/transformers/parse_address.py", line 70, in translate_item
    |     data.update(address)
    | TypeError: 'coroutine' object is not iterable
    +---------------- 10 ----------------
    | Traceback (most recent call last):
    |   File "/opt/airflow/dags/real_estates/homes_jp/transformers/parse_address.py", line 70, in translate_item
    |     data.update(address)
    | TypeError: 'coroutine' object is not iterable
    +---------------- 11 ----------------
    | Traceback (most recent call last):
    |   File "/opt/airflow/dags/real_estates/homes_jp/transformers/parse_address.py", line 70, in translate_item
    |     data.update(address)
    | TypeError: 'coroutine' object is not iterable
    +---------------- 12 ----------------
    | Traceback (most recent call last):
    |   File "/opt/airflow/dags/real_estates/homes_jp/transformers/parse_address.py", line 70, in translate_item
    |     data.update(address)
    | TypeError: 'coroutine' object is not iterable
    +---------------- 13 ----------------
    | Traceback (most recent call last):
    |   File "/opt/airflow/dags/real_estates/homes_jp/transformers/parse_address.py", line 70, in translate_item
    |     data.update(address)
    | TypeError: 'coroutine' object is not iterable
    +---------------- 14 ----------------
    | Traceback (most recent call last):
    |   File "/opt/airflow/dags/real_estates/homes_jp/transformers/parse_address.py", line 70, in translate_item
    |     data.update(address)
    | TypeError: 'coroutine' object is not iterable
    +---------------- 15 ----------------
    | Traceback (most recent call last):
    |   File "/opt/airflow/dags/real_estates/homes_jp/transformers/parse_address.py", line 70, in translate_item
    |     data.update(address)
    | TypeError: 'coroutine' object is not iterable
    +---------------- ... ----------------
    | and 3328 more exceptions
    +------------------------------------
[2024-04-08T04:58:42.530+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=real_estates, task_id=transform_parse_address, execution_date=20240408T035540, start_date=20240408T045835, end_date=20240408T045842
[2024-04-08T04:58:42.555+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 319 for task transform_parse_address (Exceptions from Trio nursery (3343 sub-exceptions); 79130)
[2024-04-08T04:58:42.603+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-08T04:58:42.659+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
