[2024-04-04T02:38:12.102+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: real_estates.load_to_mongo__2 manual__2024-04-03T10:39:54.321446+00:00 [queued]>
[2024-04-04T02:38:12.122+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: real_estates.load_to_mongo__2 manual__2024-04-03T10:39:54.321446+00:00 [queued]>
[2024-04-04T02:38:12.123+0000] {taskinstance.py:2193} INFO - Starting attempt 5 of 5
[2024-04-04T02:38:12.151+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): load_to_mongo__2> on 2024-04-03 10:39:54.321446+00:00
[2024-04-04T02:38:12.165+0000] {standard_task_runner.py:60} INFO - Started process 13289 to run task
[2024-04-04T02:38:12.173+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'real_estates', 'load_to_mongo__2', 'manual__2024-04-03T10:39:54.321446+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/real_estates/__init__.py', '--cfg-path', '/tmp/tmp_7pqaugv']
[2024-04-04T02:38:12.178+0000] {standard_task_runner.py:88} INFO - Job 150: Subtask load_to_mongo__2
[2024-04-04T02:38:12.590+0000] {task_command.py:423} INFO - Running <TaskInstance: real_estates.load_to_mongo__2 manual__2024-04-03T10:39:54.321446+00:00 [running]> on host 72a42bdc0b23
[2024-04-04T02:38:12.755+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='real_estates' AIRFLOW_CTX_TASK_ID='load_to_mongo__2' AIRFLOW_CTX_EXECUTION_DATE='2024-04-03T10:39:54.321446+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-03T10:39:54.321446+00:00'
[2024-04-04T02:38:12.759+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-04-04T02:38:12.760+0000] {base.py:83} INFO - Using connection ID '***' for task execution.
[2024-04-04T02:38:12.779+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/real_estates/homes_jp/loaders/__init__.py", line 8, in load_to_mongo
    upsert(database, collection, filter_keys, data)
  File "/opt/airflow/dags/real_estates/homes_jp/loaders/mongo.py", line 26, in upsert
    operations = [
  File "/opt/airflow/dags/real_estates/homes_jp/loaders/mongo.py", line 28, in <listcomp>
    {key: item[key] for key in filter_keys},
  File "/opt/airflow/dags/real_estates/homes_jp/loaders/mongo.py", line 28, in <dictcomp>
    {key: item[key] for key in filter_keys},
KeyError: 'url'
[2024-04-04T02:38:12.797+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=real_estates, task_id=load_to_***__2, execution_date=20240403T103954, start_date=20240404T023812, end_date=20240404T023812
[2024-04-04T02:38:12.820+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 150 for task load_to_***__2 ('url'; 13289)
[2024-04-04T02:38:12.866+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-04T02:38:12.903+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
