[2024-04-03T11:03:06.437+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: real_estates.load_to_mongo__2 manual__2024-04-03T10:39:54.321446+00:00 [queued]>
[2024-04-03T11:03:06.456+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: real_estates.load_to_mongo__2 manual__2024-04-03T10:39:54.321446+00:00 [queued]>
[2024-04-03T11:03:06.457+0000] {taskinstance.py:2193} INFO - Starting attempt 4 of 4
[2024-04-03T11:03:06.484+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): load_to_mongo__2> on 2024-04-03 10:39:54.321446+00:00
[2024-04-03T11:03:06.499+0000] {standard_task_runner.py:60} INFO - Started process 614 to run task
[2024-04-03T11:03:06.506+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'real_estates', 'load_to_mongo__2', 'manual__2024-04-03T10:39:54.321446+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/real_estates/__init__.py', '--cfg-path', '/tmp/tmppy3sd22i']
[2024-04-03T11:03:06.511+0000] {standard_task_runner.py:88} INFO - Job 142: Subtask load_to_mongo__2
[2024-04-03T11:03:06.930+0000] {task_command.py:423} INFO - Running <TaskInstance: real_estates.load_to_mongo__2 manual__2024-04-03T10:39:54.321446+00:00 [running]> on host 72a42bdc0b23
[2024-04-03T11:03:07.110+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='real_estates' AIRFLOW_CTX_TASK_ID='load_to_mongo__2' AIRFLOW_CTX_EXECUTION_DATE='2024-04-03T10:39:54.321446+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-03T10:39:54.321446+00:00'
[2024-04-03T11:03:07.113+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-04-03T11:03:07.115+0000] {base.py:83} INFO - Using connection ID '***' for task execution.
[2024-04-03T11:03:07.134+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/real_estates/homes_jp/loaders/__init__.py", line 8, in load_to_mongo
    upsert(database, collection, filter_keys, data)
  File "/opt/airflow/dags/real_estates/homes_jp/loaders/mongo.py", line 26, in upsert
    operations = [
  File "/opt/airflow/dags/real_estates/homes_jp/loaders/mongo.py", line 28, in <listcomp>
    {key: item[key] for key in filter_keys},
  File "/opt/airflow/dags/real_estates/homes_jp/loaders/mongo.py", line 28, in <dictcomp>
    {key: item[key] for key in filter_keys},
KeyError: 'url'
[2024-04-03T11:03:07.150+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=real_estates, task_id=load_to_***__2, execution_date=20240403T103954, start_date=20240403T110306, end_date=20240403T110307
[2024-04-03T11:03:07.173+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 142 for task load_to_***__2 ('url'; 614)
[2024-04-03T11:03:07.240+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-03T11:03:07.277+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
