[2024-04-08T08:38:31.561+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: real_estates.load_to_one_c manual__2024-04-08T07:30:32.722267+00:00 [queued]>
[2024-04-08T08:38:31.580+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: real_estates.load_to_one_c manual__2024-04-08T07:30:32.722267+00:00 [queued]>
[2024-04-08T08:38:31.581+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-08T08:38:31.610+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): load_to_one_c> on 2024-04-08 07:30:32.722267+00:00
[2024-04-08T08:38:31.623+0000] {standard_task_runner.py:60} INFO - Started process 627 to run task
[2024-04-08T08:38:31.631+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'real_estates', 'load_to_one_c', 'manual__2024-04-08T07:30:32.722267+00:00', '--job-id', '347', '--raw', '--subdir', 'DAGS_FOLDER/real_estates/__init__.py', '--cfg-path', '/tmp/tmpqqb01bou']
[2024-04-08T08:38:31.636+0000] {standard_task_runner.py:88} INFO - Job 347: Subtask load_to_one_c
[2024-04-08T08:38:32.040+0000] {task_command.py:423} INFO - Running <TaskInstance: real_estates.load_to_one_c manual__2024-04-08T07:30:32.722267+00:00 [running]> on host 0a1174cdb8a2
[2024-04-08T08:38:32.338+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='real_estates' AIRFLOW_CTX_TASK_ID='load_to_one_c' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T07:30:32.722267+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-08T07:30:32.722267+00:00'
[2024-04-08T08:38:32.343+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/real_estates/homes_jp/loaders/__init__.py", line 15, in load_to_one_c
    asyncio.run(one_c(data))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/airflow/dags/real_estates/homes_jp/loaders/one_c.py", line 7, in one_c
    async with aiohttp.ClientSession("http://103.157.218.115/RealEstate/hs/RealEstate/V1/RealEstate") as session:
  File "/home/airflow/.local/lib/python3.8/site-packages/aiohttp/client.py", line 247, in __init__
    assert (
AssertionError: Only absolute URLs without path part are supported
[2024-04-08T08:38:32.362+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=real_estates, task_id=load_to_one_c, execution_date=20240408T073032, start_date=20240408T083831, end_date=20240408T083832
[2024-04-08T08:38:32.384+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 347 for task load_to_one_c (Only absolute URLs without path part are supported; 627)
[2024-04-08T08:38:32.444+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-08T08:38:32.769+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
