[2024-04-08T03:00:27.831+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: real_estates.load_to_mongo__2 scheduled__2024-04-06T00:00:00+00:00 [queued]>
[2024-04-08T03:00:27.850+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: real_estates.load_to_mongo__2 scheduled__2024-04-06T00:00:00+00:00 [queued]>
[2024-04-08T03:00:27.851+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-04-08T03:00:27.878+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): load_to_mongo__2> on 2024-04-06 00:00:00+00:00
[2024-04-08T03:00:27.892+0000] {standard_task_runner.py:60} INFO - Started process 77343 to run task
[2024-04-08T03:00:27.899+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'real_estates', 'load_to_mongo__2', 'scheduled__2024-04-06T00:00:00+00:00', '--job-id', '276', '--raw', '--subdir', 'DAGS_FOLDER/real_estates/__init__.py', '--cfg-path', '/tmp/tmp_f71zcwc']
[2024-04-08T03:00:27.905+0000] {standard_task_runner.py:88} INFO - Job 276: Subtask load_to_mongo__2
[2024-04-08T03:00:28.318+0000] {task_command.py:423} INFO - Running <TaskInstance: real_estates.load_to_mongo__2 scheduled__2024-04-06T00:00:00+00:00 [running]> on host 05a350db99a0
[2024-04-08T03:00:28.551+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='real_estates' AIRFLOW_CTX_TASK_ID='load_to_mongo__2' AIRFLOW_CTX_EXECUTION_DATE='2024-04-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-06T00:00:00+00:00'
[2024-04-08T03:00:28.554+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-04-08T03:00:28.555+0000] {base.py:83} INFO - Using connection ID '***' for task execution.
[2024-04-08T03:00:28.577+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/real_estates/homes_jp/loaders/__init__.py", line 8, in load_to_mongo
    upsert(collection, filter_keys, data)
  File "/opt/airflow/dags/real_estates/homes_jp/loaders/mongo.py", line 23, in upsert
    if isinstance(data[0], dict):
IndexError: list index out of range
[2024-04-08T03:00:28.598+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=real_estates, task_id=load_to_***__2, execution_date=20240406T000000, start_date=20240408T030027, end_date=20240408T030028
[2024-04-08T03:00:28.622+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 276 for task load_to_***__2 (list index out of range; 77343)
[2024-04-08T03:00:28.677+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-08T03:00:29.303+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
