[2024-04-08T03:27:35.174+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: real_estates.extract_real_estates scheduled__2024-04-06T00:00:00+00:00 [queued]>
[2024-04-08T03:27:35.194+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: real_estates.extract_real_estates scheduled__2024-04-06T00:00:00+00:00 [queued]>
[2024-04-08T03:27:35.194+0000] {taskinstance.py:2193} INFO - Starting attempt 8 of 8
[2024-04-08T03:27:35.222+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): extract_real_estates> on 2024-04-06 00:00:00+00:00
[2024-04-08T03:27:35.236+0000] {standard_task_runner.py:60} INFO - Started process 77776 to run task
[2024-04-08T03:27:35.244+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'real_estates', 'extract_real_estates', 'scheduled__2024-04-06T00:00:00+00:00', '--job-id', '291', '--raw', '--subdir', 'DAGS_FOLDER/real_estates/__init__.py', '--cfg-path', '/tmp/tmpd30nsgir']
[2024-04-08T03:27:35.249+0000] {standard_task_runner.py:88} INFO - Job 291: Subtask extract_real_estates
[2024-04-08T03:27:35.658+0000] {task_command.py:423} INFO - Running <TaskInstance: real_estates.extract_real_estates scheduled__2024-04-06T00:00:00+00:00 [running]> on host 05a350db99a0
[2024-04-08T03:27:36.234+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='real_estates' AIRFLOW_CTX_TASK_ID='extract_real_estates' AIRFLOW_CTX_EXECUTION_DATE='2024-04-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-06T00:00:00+00:00'
[2024-04-08T03:27:45.676+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-04-08T03:27:45.679+0000] {process_utils.py:131} INFO - Sending 15 to group 77776. PIDs of all processes in the group: [77776]
[2024-04-08T03:27:45.680+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 77776
[2024-04-08T03:27:45.680+0000] {taskinstance.py:2483} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-04-08T03:27:45.681+0000] {streams.py:168} ERROR - Exception in eof callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/aiohttp/streams.py", line 166, in on_eof
    callback()
  File "/home/airflow/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1017, in _response_eof
    self._release_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1071, in _release_connection
    self._connection.release()
  File "/home/airflow/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 174, in release
    self._key, self._protocol, should_close=self._protocol.should_close
  File "/home/airflow/.local/lib/python3.8/site-packages/aiohttp/client_proto.py", line 55, in should_close
    or len(self) > 0
  File "/home/airflow/.local/lib/python3.8/site-packages/aiohttp/streams.py", line 580, in __len__
    return len(self._buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-04-08T03:27:50.378+0000] {real_estates.py:37} INFO - Batch 1/1 fetched 3600 pages
[2024-04-08T03:27:55.111+0000] {real_estates.py:75} INFO - Real estate not found: https://www.homes.co.jp/kodate/b-17073810001471/
[2024-04-08T03:28:02.312+0000] {real_estates.py:75} INFO - Real estate not found: https://www.homes.co.jp/kodate/b-17073820001226/
[2024-04-08T03:28:24.070+0000] {real_estates.py:75} INFO - Real estate not found: https://www.homes.co.jp/kodate/b-17074100000499/
[2024-04-08T03:28:24.556+0000] {real_estates.py:75} INFO - Real estate not found: https://www.homes.co.jp/tochi/b-17069230000146/
[2024-04-08T03:28:45.703+0000] {process_utils.py:149} WARNING - process psutil.Process(pid=77776, name='airflow task ru', status='running', started='03:27:34') did not respond to SIGTERM. Trying SIGKILL
[2024-04-08T03:28:45.705+0000] {process_utils.py:86} INFO - Sending the signal 9 to group 77776
[2024-04-08T03:28:45.798+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=77776, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='03:27:34') (77776) terminated with exit code -9
[2024-04-08T03:28:45.799+0000] {standard_task_runner.py:175} ERROR - Job 291 was killed before it finished (likely due to running out of memory)
